version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    platform: linux/arm64
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:latest
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aurora_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - REDIS_URI=redis://redis:6379
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - qdrant
      - redis

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aurora_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  qdrant_data:
  redis_data:
